name: obfuscale
channels: [conda-forge, defaults]
dependencies:
  - python>=3.10
  - pip
  - numpy
  - pandas
  - pyyaml
  - pillow
  - matplotlib
  - scikit-learn
  - pip:
      - typer>=0.12
      - pre-commit
      - ruff
      - black
      - nbstripout
      - detect-secrets
